"""Emit an auditable survey as LaTeX, BibTeX, and JSON sidecars."""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping

from src.core.events import canonical_json
from .corpus import coverage_report
from .extraction import ExtractionResult, relation_table
from .gaps import CandidateSet, GapResult, gap_table, novelty_audit
from .records import DocumentRecord, SurveyContractError, SurveyCorpus

_LATEX_ESCAPES = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
_LATEX_PATTERN = re.compile("|".join(re.escape(x) for x in _LATEX_ESCAPES))
_TRANSLATIONS = {
    "\u2010": "-", "\u2011": "-", "\u2012": "--", "\u2013": "--", "\u2014": "---",
    "\u2018": "`", "\u2019": "'", "\u201c": "``", "\u201d": "''",
    "\u2032": r"$'$", "\u2033": r"$''$", "\u00b0": r"\textdegree{}", "\u2212": "$-$",
    "\u00d7": r"$\times$", "\u00b7": r"$\cdot$", "\u2026": r"\ldots{}",
    "\u2248": r"$\approx$", "\u2264": r"$\leq$", "\u2265": r"$\geq$", "\u2260": r"$\neq$",
    "\u00b1": r"$\pm$", "\u2192": r"$\rightarrow$", "\u2194": r"$\leftrightarrow$",
    "\u03b1": r"$\alpha$", "\u03b2": r"$\beta$", "\u03b3": r"$\gamma$", "\u03b4": r"$\delta$",
    "\u03ba": r"$\kappa$", "\u03bb": r"$\lambda$", "\u03bc": r"$\mu$", "\u03c3": r"$\sigma$",
    "\u03a9": r"$\Omega$", "\u00c5": r"\AA{}", "\u212b": r"\AA{}",
    "\u2080": "$_0$", "\u2081": "$_1$", "\u2082": "$_2$", "\u2083": "$_3$", "\u2084": "$_4$", "\u2085": "$_5$", "\u2086": "$_6$",
    "\u00b9": "$^1$", "\u00b2": "$^2$", "\u00b3": "$^3$", "\u00a0": " ",
}
_TRANSLATION_TABLE = {ord(k): v for k, v in _TRANSLATIONS.items()}
MAX_TABLE_ROWS = 60
_CITE = re.compile(r"\\cite\{([^}]*)\}")
_BIB_ENTRY = re.compile(r"^@\w+\{([^,]+),", re.MULTILINE)


def latex_escape(text: Any) -> str:
    return _LATEX_PATTERN.sub(lambda m: _LATEX_ESCAPES[m.group()], str(text).translate(_TRANSLATION_TABLE))


def unsupported_characters(text: str) -> list[str]:
    return sorted({c for c in str(text).translate(_TRANSLATION_TABLE) if ord(c) > 127})


def citation_keys(documents: Mapping[str, DocumentRecord]) -> dict[str, str]:
    result, seen = {}, {}
    for doc_id in sorted(documents):
        base = documents[doc_id].bib_key()
        count = seen.get(base, 0)
        seen[base] = count + 1
        result[doc_id] = base if count == 0 else f"{base}x{count}"
    return result


def _bib_field(name: str, value: Any) -> str:
    return f"  {name} = {{{latex_escape(value)}}},\n"


def build_bibliography(documents: Mapping[str, DocumentRecord], keys: Mapping[str, str]) -> str:
    chunks = ["% Generated by VeriMat.\n", "% Every body citation has one entry.\n\n"]
    for doc_id in sorted(documents):
        record = documents[doc_id]
        text = f"@article{{{keys[doc_id]},\n  title = {{{{{latex_escape(record.title)}}}}},\n"
        if record.venue:
            text += _bib_field("journal", record.venue)
        if record.year:
            text += f"  year = {{{int(record.year)}}},\n"
        if record.doi:
            text += _bib_field("doi", record.doi)
        text += _bib_field("note", f"{record.database} doc_id {record.doc_id}")
        chunks.append(text.rstrip(",\n") + "\n}\n\n")
    return "".join(chunks)


PREAMBLE = r"""% Generated by VeriMat.
\documentclass[11pt,a4paper]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[margin=25mm]{geometry}
\usepackage{longtable}
\usepackage{booktabs}
\usepackage[hidelinks]{hyperref}
\pdfinfoomitdate=1
\pdftrailerid{}
\pdfsuppressptexinfo=-1
"""
BUILD_SCRIPT = '''"""Compile the report reproducibly."""
from __future__ import annotations
import os, shutil, subprocess
from pathlib import Path
SOURCE_DATE_EPOCH = "1755000000"
root = Path(__file__).resolve().parent
env = dict(os.environ)
env["SOURCE_DATE_EPOCH"] = SOURCE_DATE_EPOCH
env["FORCE_SOURCE_DATE"] = "1"
latex, bibtex = shutil.which("pdflatex"), shutil.which("bibtex")
if latex is None or bibtex is None:
    raise SystemExit("pdflatex and bibtex are required")
for command in ([latex, "-interaction=nonstopmode", "-halt-on-error", "survey"], [bibtex, "survey"], [latex, "-interaction=nonstopmode", "-halt-on-error", "survey"], [latex, "-interaction=nonstopmode", "-halt-on-error", "survey"]):
    subprocess.run(command, cwd=root, env=env, check=True)
'''
MAKEFILE = """SOURCE_DATE_EPOCH := 1755000000
export SOURCE_DATE_EPOCH
export FORCE_SOURCE_DATE := 1
survey.pdf: survey.tex references.bib
\tpdflatex -interaction=nonstopmode -halt-on-error survey
\tbibtex survey
\tpdflatex -interaction=nonstopmode -halt-on-error survey
\tpdflatex -interaction=nonstopmode -halt-on-error survey
clean:
\trm -f survey.aux survey.bbl survey.blg survey.log survey.out survey.toc survey.pdf
.PHONY: clean
"""


def _row(cells: Iterable[Any]) -> str:
    return " & ".join(latex_escape(x) for x in cells) + r" \\" + "\n"


def _cite(doc_keys: Iterable[str], keys: Mapping[str, str]) -> str:
    chosen = [keys[x] for x in dict.fromkeys(doc_keys) if x in keys]
    return "\\cite{" + ",".join(chosen) + "}" if chosen else ""


@dataclass
class SurveyReport:
    files: dict[str, str] = field(default_factory=dict)
    audit: dict[str, Any] = field(default_factory=dict)

    def write(self, root: Any) -> list[str]:
        from src.core.portability import extended_path
        if not self.audit.get("verified"):
            raise SurveyContractError("report citations failed verification: " + canonical_json(self.audit.get("failures", [])))
        target = extended_path(root)
        target.mkdir(parents=True, exist_ok=True)
        for name, content in sorted(self.files.items()):
            (target / name).write_text(content, encoding="utf-8", newline="\n")
        return sorted(self.files)


def verify(*, corpus: SurveyCorpus, extraction: ExtractionResult, gaps: GapResult, tex: str, bib: str, keys: Mapping[str, str]) -> dict[str, Any]:
    failures = []
    def fail(check: str, detail: str) -> None:
        failures.append({"check": check, "detail": detail})
    for relation_id, relation in sorted(extraction.relations.items()):
        passage = corpus.passages.get(relation.passage_id)
        if passage is None:
            fail("relation_passage_present", f"{relation_id} cites {relation.passage_id}")
        elif not passage.supports_quote(relation.quote):
            fail("relation_quote_literal", relation_id)
        elif corpus.document_for(passage) is None:
            fail("relation_document_present", relation_id)
    for gap_id, gap in sorted(gaps.gaps.items()):
        cited = [x for x in gap.supporting_passages if x in corpus.passages]
        if len(cited) != len(gap.supporting_passages):
            fail("gap_passages_present", gap_id)
        if gap.novelty == "known" and not any(corpus.passages[x].supports_quote(gap.novelty_quote) for x in cited):
            fail("gap_novelty_quote_literal", gap_id)
    cited_keys = {x.strip() for group in _CITE.findall(tex) for x in group.split(",") if x.strip()}
    bib_keys = set(_BIB_ENTRY.findall(bib))
    for key in sorted(cited_keys - bib_keys):
        fail("citation_has_entry", key)
    for key in sorted(bib_keys - cited_keys):
        fail("entry_is_cited", key)
    reverse = {value: key for key, value in keys.items()}
    for key in sorted(bib_keys):
        record = corpus.documents.get(reverse.get(key, ""))
        if record is None:
            fail("entry_has_document", key)
        elif not record.is_citable():
            fail("entry_is_findable", key)
    return {"verified": not failures, "n_checks_failed": len(failures), "failures": failures,
            "n_relations_checked": len(extraction.relations), "n_gaps_checked": len(gaps.gaps),
            "n_citations_in_body": len(cited_keys), "n_bibliography_entries": len(bib_keys),
            "citations_match_bibliography": not any(x["check"] in {"citation_has_entry", "entry_is_cited"} for x in failures),
            "characters_pdflatex_cannot_set": sorted({c for text in (tex, bib) for c in unsupported_characters(text)}),
            "novelty_audit": novelty_audit(gaps, corpus)}


def _scope_section(corpus: SurveyCorpus, coverage: Mapping[str, Any]) -> str:
    topic = corpus.topic
    protocol = coverage["protocol"]
    return ("\\section{Scope and retrieval protocol}\n" + f"Topic: {latex_escape(topic.title)}. "
            f"Language: {latex_escape(topic.language)}. Years: {topic.year_from}--{topic.year_to}. "
            f"Databases: {latex_escape(', '.join(coverage['databases']))}. Fingerprint: "
            f"\\texttt{{{latex_escape(coverage['topic_fingerprint'])}}}.\n\n"
            f"Stage one: {latex_escape(protocol['stage_one'])}; passes: "
            f"{latex_escape(protocol['stage_one_passes'])}. Stage two: "
            f"{latex_escape(protocol['stage_two'])}. {latex_escape(protocol['anchoring_bias'].capitalize())}.\n\n"
            "The stages are not interchangeable. Semantic retrieval on this deployment enforces "
            "exactly one hard constraint, the document scope, so the year and language envelope is "
            "a property of the corpus only because the metadata stage established it first.\n\n")


def _coverage_section(coverage: Mapping[str, Any]) -> str:
    out = "\\section{Coverage}\n\\begin{tabular}{lr}\n\\toprule\nQuantity & Value \\\\\n\\midrule\n"
    for label, key in (("Queries", "n_queries"), ("Empty queries", "n_empty_queries"), ("Saturated queries", "n_saturated_queries"), ("Documents", "n_documents"), ("Citable documents", "n_citable_documents"), ("Documents with evidence", "n_documents_with_evidence"), ("Unread documents", "n_documents_unread"), ("Passages", "n_passages")):
        out += _row((label, coverage[key]))
    span = coverage["year_span"]
    out += _row(("Year span", f"{span[0]}--{span[1]}")) + "\\bottomrule\n\\end{tabular}\n\n"
    total = max(1, int(coverage["n_documents"]))
    out += f"{coverage['n_documents_unread']} of {coverage['n_documents']} documents ({100 * coverage['n_documents_unread'] / total:.1f} per cent) were unread; negative claims are bounded by this fraction.\n\n"
    if coverage["queries_returning_nothing"]:
        out += "Queries returning nothing:\n\\begin{itemize}\n" + "".join(f"\\item {latex_escape(x)}\n" for x in coverage["queries_returning_nothing"]) + "\\end{itemize}\n"
    return out + "\n"


def _gate_section(extraction: Mapping[str, Any], candidates: Mapping[str, Any]) -> str:
    out = "\\section{Deterministic gates}\nA language model proposed relations; none was admitted on its word.\n\n\\begin{tabular}{lr}\n\\toprule\nQuantity & Value \\\\\n\\midrule\n"
    for label, key in (("Proposed", "n_proposed"), ("Admitted", "n_admitted"), ("Rejected", "n_rejected"), ("Admission rate", "admission_rate")):
        out += _row((label, extraction[key]))
    for key, value in sorted(extraction["rejections_by_reason"].items()):
        out += _row((f"Rejected: {key}", value))
    out += _row(("Gap candidates", candidates["n_candidates"])) + _row(("Cap suppressions", candidates["suppressed_by_per_kind_cap"]))
    return out + "\\bottomrule\n\\end{tabular}\n\n"


def _relation_section(rows: list[Mapping[str, Any]], keys: Mapping[str, str], max_rows: int) -> str:
    out = "\\section{Structure--property relations}\n\\begin{longtable}{p{22mm}p{26mm}p{24mm}p{16mm}p{20mm}p{14mm}l}\n\\toprule\nMaterial & Feature & Property & Direction & Value & Method & Source \\\\\n\\midrule\n\\endfirsthead\\toprule\nMaterial & Feature & Property & Direction & Value & Method & Source \\\\\n\\midrule\\endhead\\bottomrule\\endfoot\n"
    for row in rows[:max_rows]:
        value = f"{row['value']} {row['unit']}".strip()
        if row["temperature_k"]:
            value += f" at {row['temperature_k']} K"
        cells = (row["material"], row["structural_feature"], row["property_name"], row["direction"], value, row["method"])
        out += " & ".join(latex_escape(x) for x in cells) + " & " + _cite([row["evidence"]["doc_id"]], keys) + r" \\" + "\n"
    out += "\\end{longtable}\n\n"
    if len(rows) > max_rows:
        out += f"{len(rows) - max_rows} further relations are retained in relations.json and the evidence chain.\n\n"
    return out


def _gap_section(rows: list[Mapping[str, Any]], keys: Mapping[str, str]) -> str:
    out = "\\section{Research gaps}\n"
    for row in rows:
        out += f"\\subsection*{{{latex_escape(row['statement'][:80])}}}\n\\textbf{{Gap.}} {latex_escape(row['statement'])}\n\n"
        out += f"\\textbf{{Status.}} {latex_escape(row['novelty'])}; {latex_escape(row['novelty_basis'])}.\n"
        if row["novelty_quote"]:
            out += "\\begin{quote}" + latex_escape(row["novelty_quote"]) + "\\end{quote}\n"
        derivation = row["derivation"]
        out += f"\\textbf{{Derivation.}} {latex_escape(derivation['rule'])}; {latex_escape(derivation['subject'])}; {latex_escape('; '.join(map(str, derivation['facts'])))}.\n"
        evidence = row["evidence"]
        out += f"\\textbf{{Evidence.}} {len(evidence)} passages {_cite([x['doc_id'] for x in evidence], keys)}; identifier \\texttt{{{latex_escape(row['gap_id'])}}}.\n\n"
    return out


def _chain_section(rows: list[Mapping[str, Any]], keys: Mapping[str, str]) -> str:
    out = "\\section{Evidence chain}\n\\label{sec:chain}\n"
    for row in rows:
        evidence = row["evidence"]
        out += f"\\noindent\\texttt{{{latex_escape(row['relation_id'])}}} {_cite([evidence['doc_id']], keys)}\n\\begin{{quote}}{latex_escape(row['quote'])}\\end{{quote}}\n"
        parts = [evidence["database"], evidence["doc_id"], evidence["passage_id"], str(evidence["content_sha256"])[:16], evidence["query_id"]]
        out += "{\\small " + latex_escape("; ".join(map(str, parts))) + "}\n\n"
    return out


def _disclosure_section(audit: Mapping[str, Any], extraction: Mapping[str, Any], gaps: Mapping[str, Any], coverage: Mapping[str, Any], model_route: str) -> str:
    novelty = audit["novelty_audit"]
    out = f"\\section{{Disclosure and verification}}\nLiterature source: Sciverse API. Model route: {latex_escape(model_route)}. Deterministic gates decide admissibility.\n\n\\begin{{tabular}}{{lr}}\n\\toprule\nCheck & Result \\\\\n\\midrule\n"
    for label, value in (("Relations checked", audit["n_relations_checked"]), ("Gaps checked", audit["n_gaps_checked"]), ("Body citations", audit["n_citations_in_body"]), ("Bibliography entries", audit["n_bibliography_entries"]), ("Failures", audit["n_checks_failed"]), ("Known gaps", novelty["n_known"]), ("New gaps", novelty["n_new"]), ("Novelty verified", novelty["verified"]), ("Extraction calls", extraction["model_calls"]), ("Gap calls", gaps["model_calls"])):
        out += _row((label, value))
    return out + "\\bottomrule\n\\end{tabular}\n\n"


def build_report(*, corpus: SurveyCorpus, extraction: ExtractionResult, candidates: CandidateSet, gaps: GapResult, title: str, author: str = "taiwanhuachenyu", report_date: str = "", model_route: str = "claude-code", max_table_rows: int = MAX_TABLE_ROWS) -> SurveyReport:
    coverage = coverage_report(corpus)
    relations = relation_table(extraction, corpus)
    gap_rows = gap_table(gaps, candidates, corpus)
    cited = {str(x["evidence"]["doc_id"]) for x in relations}
    cited.update(str(x["doc_id"]) for row in gap_rows for x in row["evidence"])
    documents = {doc_id: record for doc_id, record in corpus.documents.items() if doc_id in cited and record.is_citable()}
    keys = citation_keys(documents)
    tex = PREAMBLE + f"\\title{{{latex_escape(title)}}}\n\\author{{{latex_escape(author)}}}\n\\date{{{latex_escape(report_date)}}}\n\\begin{{document}}\n\\maketitle\n\\tableofcontents\n\n"
    tex += _scope_section(corpus, coverage) + _coverage_section(coverage) + _gate_section(extraction.manifest(), candidates.manifest())
    tex += _relation_section(relations, keys, max_table_rows) + _gap_section(gap_rows, keys) + _chain_section(relations, keys)
    bib = build_bibliography(documents, keys)
    audit = verify(corpus=corpus, extraction=extraction, gaps=gaps, tex=tex, bib=bib, keys=keys)
    audit["documents_cited_but_not_citable"] = sorted(cited - set(documents))
    tex += _disclosure_section(audit, extraction.manifest(), gaps.manifest(), coverage, model_route)
    tex += "\\bibliographystyle{unsrt}\n\\bibliography{references}\n\\end{document}\n"
    files = {"survey.tex": tex, "references.bib": bib, "build.py": BUILD_SCRIPT, "Makefile": MAKEFILE,
             "coverage.json": canonical_json(coverage) + "\n", "relations.json": canonical_json(relations) + "\n",
             "gaps.json": canonical_json(gap_rows) + "\n", "verification.json": canonical_json(audit) + "\n",
             "extraction_gates.json": canonical_json({"extraction": extraction.manifest(), "candidates": candidates.manifest(), "gaps": gaps.manifest(), "rejected_proposals": [item.__dict__ for item in extraction.rejections], "refused_candidates": [item.__dict__ for item in gaps.refused], "dropped_by_gate": list(gaps.dropped)}) + "\n"}
    return SurveyReport(files=files, audit=audit)
